SELECT TOP (1000) [MES]
      ,[ID_CLIENTE]
  FROM [NOS].[dbo].[SOCIOS] S
WHERE S.ID_CLIENTE = 'C10502'


  SELECT 
	--S.MES,
	S.ID_CLIENTE,
	COUNT( S.ID_CLIENTE ) AS Count
  FROM DBO.SOCIOS S
  GROUP BY /*S.MES , */S.ID_CLIENTE ORDER BY  COUNT( S.ID_CLIENTE ) DESC
