SELECT *
FROM DBO.VENDAS_SAC VS
WHERE CHARINDEX( '+' , VS.PACOTES_VENDIDOS )  > 0 

-- 39 LINHAS A ESQUERDA DO '+'
-- 39 LINHAS A DIREITA DO '+'
-- 85 LINHAS SEM '+'

ALTER VIEW  VENDAS_SAC_Cleaned AS

WITH A AS(
	SELECT 
		VS.DATA_VENDA,
		VS.ID_CLIENTE,
		LEFT( VS.PACOTES_VENDIDOS , CHARINDEX( '+' , VS.PACOTES_VENDIDOS ) - 1 ) AS PACOTES_VENDIDOS

	FROM DBO.VENDAS_SAC VS
	WHERE CHARINDEX( '+' , VS.PACOTES_VENDIDOS ) > 0 
),

B AS(
	SELECT 
		VS.DATA_VENDA,
		VS.ID_CLIENTE,
		RIGHT( VS.PACOTES_VENDIDOS , LEN( VS.PACOTES_VENDIDOS ) - CHARINDEX( '+' , VS.PACOTES_VENDIDOS )  ) AS PACOTES_VENDIDOS
		

		FROM DBO.VENDAS_SAC VS
		WHERE CHARINDEX( '+' , VS.PACOTES_VENDIDOS ) > 0 
),
C AS (

	SELECT 
		VS.DATA_VENDA,
		VS.ID_CLIENTE,
		LEFT( VS.PACOTES_VENDIDOS , CHARINDEX( '|',VS.PACOTES_VENDIDOS  ) - 1) AS DESTINOS,
		RIGHT( VS.PACOTES_VENDIDOS , LEN( VS.PACOTES_VENDIDOS ) - CHARINDEX( '|' , VS.PACOTES_VENDIDOS )  ) AS QTDE
	FROM DBO.VENDAS_SAC VS
	WHERE CHARINDEX( '+' , VS.PACOTES_VENDIDOS ) = 0 


)

SELECT 
	A.DATA_VENDA,
	A.ID_CLIENTE,
	LEFT( A.PACOTES_VENDIDOS, CHARINDEX( '|' , A.PACOTES_VENDIDOS ) - 1) AS DESTINOS
	--RIGHT( A.PACOTES_VENDIDOS, LEN( A.PACOTES_VENDIDOS ) - CHARINDEX( '|' , A.PACOTES_VENDIDOS ) ) AS QTDE
	
FROM A
	CROSS APPLY STRING_SPLIT( RIGHT( A.PACOTES_VENDIDOS, LEN( A.PACOTES_VENDIDOS ) - CHARINDEX( '|' , A.PACOTES_VENDIDOS ) ) , '2' ) 


UNION ALL 


SELECT 
	B.DATA_VENDA,
	B.ID_CLIENTE,
	LEFT( B.PACOTES_VENDIDOS , CHARINDEX( '|' , B.PACOTES_VENDIDOS ) - 1) AS DESTINOS
	--RIGHT( B.PACOTES_VENDIDOS , LEN( B.PACOTES_VENDIDOS ) -  CHARINDEX( '|' , B.PACOTES_VENDIDOS ) ) AS QTDE
FROM B
	CROSS APPLY string_split( RIGHT( B.PACOTES_VENDIDOS , LEN( B.PACOTES_VENDIDOS ) -  CHARINDEX( '|' , B.PACOTES_VENDIDOS ) ) , '2' )

UNION ALL 

	SELECT 
		C.DATA_VENDA,
		C.ID_CLIENTE,
		C.DESTINOS
	FROM C
	CROSS APPLY string_split( C.QTDE, '2' )

;