CREATE VIEW fVendas AS
WITH A AS(
SELECT * 
FROM
(SELECT * 
FROM [dbo].[VENDAS_LOJAS_Cleaned]

UNION ALL

SELECT * 
FROM [dbo].[VENDAS_OUTBOUND_Cleaned]

UNION ALL

SELECT *
FROM [dbo].[VENDAS_SAC_Cleaned] ) AS A LEFT JOIN DBO.CATALOGO_PACOTES CP 
ON YEAR( A.DATA_VENDA ) = CAST( LEFT( CP.MES , 4 ) AS INT ) AND MONTH( A.DATA_VENDA ) = CAST( RIGHT( CP.MES, 2 ) AS INT ) AND A.DESTINOS = CP.DESC_PACOTE
),
B AS (

SELECT 
	A.DATA_VENDA,
	A.ID_CLIENTE,
	A.DESTINOS,
	A.PRECO,
	B.TEMPO_COMO_CLIENTE,
		CASE
			WHEN B.TEMPO_COMO_CLIENTE = 1 AND MONTH( A.DATA_VENDA ) = ( SELECT MAX( MONTH( A.DATA_VENDA ) )  FROM A ) THEN 'New'
			WHEN B.TEMPO_COMO_CLIENTE IS NULL THEN 'Not Member'
		ELSE 'Old'
		END AS TIPO_CLIENTE,
	ROW_NUMBER() OVER( PARTITION BY A.ID_CLIENTE ORDER BY A.PRECO DESC ) AS NUMERO_COMPRA
FROM A LEFT JOIN (SELECT 
					S.ID_CLIENTE,
					COUNT( S.ID_CLIENTE ) AS TEMPO_COMO_CLIENTE
					FROM DBO.SOCIOS S
					GROUP BY S.ID_CLIENTE ) AS B ON A.ID_CLIENTE = B.ID_CLIENTE
)

, C AS(
SELECT *,
	CASE
		WHEN B.NUMERO_COMPRA = 1 AND B.TIPO_CLIENTE = 'Old' OR B.NUMERO_COMPRA = 1 AND B.TIPO_CLIENTE = 'New'  THEN  10
		WHEN B.NUMERO_COMPRA > 1 AND B.TIPO_CLIENTE = 'Old' OR B.NUMERO_COMPRA > 1 AND B.TIPO_CLIENTE = 'New'  THEN  10 + ( B.NUMERO_COMPRA * 2 - 2 ) 
	ELSE '-'
	END DESCONTO_SOCIOS
FROM B )

SELECT *,
	C.PRECO - ( C.PRECO * C.DESCONTO_SOCIOS / 100  ) AS VALOR_FINAL,
	CASE	
		WHEN C.TIPO_CLIENTE = 'New' THEN 100 
		WHEN C.TIPO_CLIENTE = 'Old' AND C.TEMPO_COMO_CLIENTE = 1 AND MONTH( C.DATA_VENDA ) = ( SELECT MAX( MONTH( C.DATA_VENDA ) ) FROM C  ) - 1  THEN 100
		WHEN C.TIPO_CLIENTE = 'Old' AND C.TEMPO_COMO_CLIENTE > 1 THEN 20
	ELSE 0
	END AS FEE_MENSAL
FROM C;


