SELECT * 
FROM VENDAS_OUTBOUND VO
WHERE CHARINDEX( '+' , VO.PACOTES_VENDIDOS)  = 0  

-- 42 LINHAS A ESQUERDA DO '+'
-- 42 LINHAS A DIREITA DO '+'
-- 98 LINHAS SEM '+'

ALTER VIEW VENDAS_OUTBOUND_Cleaned AS
	WITH A AS(
	SELECT
		VO.DATA_VENDA,
		VO.ID_CLIENTE,
		LEFT( VO.PACOTES_VENDIDOS , CHARINDEX('+' , VO.PACOTES_VENDIDOS) - 1 ) AS DESTINO

	FROM DBO.VENDAS_OUTBOUND VO
	WHERE CHARINDEX( '+' , VO.PACOTES_VENDIDOS) > 0 
	),
	B AS(

	SELECT
		VO.DATA_VENDA,
		VO.ID_CLIENTE,
		RIGHT( VO.PACOTES_VENDIDOS , LEN(VO.PACOTES_VENDIDOS) - CHARINDEX('+' , VO.PACOTES_VENDIDOS)  ) AS DESTINO

	FROM DBO.VENDAS_OUTBOUND VO
	WHERE CHARINDEX( '+' , VO.PACOTES_VENDIDOS) > 0

	),

	C AS (

		SELECT 
			VO.DATA_VENDA,
			VO.ID_CLIENTE,
			LEFT( VO.PACOTES_VENDIDOS , CHARINDEX( '|' , VO.PACOTES_VENDIDOS ) - 1 ) AS DESTINOS,
			RIGHT( VO.PACOTES_VENDIDOS, LEN( VO.PACOTES_VENDIDOS ) -  CHARINDEX( '|' , VO.PACOTES_VENDIDOS ) ) AS QTDE
		FROM VENDAS_OUTBOUND VO
		WHERE CHARINDEX( '+' , VO.PACOTES_VENDIDOS ) = 0
	)


	SELECT 
		A.DATA_VENDA,
		A.ID_CLIENTE,
		LEFT( A.DESTINO , CHARINDEX( '|' , A.DESTINO ) - 1 ) AS DESTINO
		--RIGHT( A.DESTINO , LEN( A.DESTINO ) - CHARINDEX( '|' , A.DESTINO ) ) AS QTDE
	FROM A
		CROSS APPLY string_split( RIGHT( A.DESTINO , LEN( A.DESTINO ) - CHARINDEX( '|' , A.DESTINO ) ) , '2' )

	UNION ALL 

	SELECT
		B.DATA_VENDA,
		B.ID_CLIENTE,
		LEFT( B.DESTINO , CHARINDEX( '|' , B.DESTINO ) - 1 ) AS DESTINO
		--RIGHT( B.DESTINO , LEN( B.DESTINO ) - CHARINDEX( '|' , B.DESTINO ) ) AS QTDE
	FROM B
		CROSS APPLY string_split( RIGHT( B.DESTINO , LEN( B.DESTINO ) - CHARINDEX( '|' , B.DESTINO ) ) , '2' )

	UNION ALL

	SELECT
		C.DATA_VENDA,
		C.ID_CLIENTE,
		C.DESTINOS
	FROM C 
		CROSS APPLY string_split( C.QTDE, '2' )


